### ISSUE TITLE
AvZ::OpenMultipleEffective()不稳定

### ISSUE THREAD

**Issue by NoReligion** [vector-wlc/AsmVsZombies#2]
可能是我电脑性能问题，多次生效有时甚至根本没有触发，即使删除源代码对应的按键绑定，仍然会在不确定但有限次重新进入EL内失效。

**Comment by vector-wlc** [comment]
抱歉，我不咋看Github的issue的，没注意到你的问题，鉴于时间久远，版本更新迭代了非常多，关于多次生效的逻辑代码早已改变，这个问题可能已经失去了意义。
