### ISSUE TITLE
为什么不选卡，AConnect会弹出警告。

### ISSUE THREAD

**Issue by zzfhadr** [vector-wlc/AsmVsZombies#4]
如果进入暂停的游戏，并且代码里没有选卡，大概率会弹出警告。。，选卡了就不会。。

**Comment by alumkal** [comment]
弹出的警告内容是什么？

**Comment by zzfhadr** [comment]
![image](https://github.com/vector-wlc/AsmVsZombies/assets/57316428/6bb6c3fe-1c63-4709-9fdd-44667422b38d)
就这样，。。 用的是示例脚本。，，

**Comment by vector-wlc** [comment]
这个是因为选卡函数中包含对 pvz 时间状态的更新函数，注释了选卡函数 avz 将不会对时间状态进行更新，因此导致报错，算是一个 bug，下一个版本将会对其进行修复
